version: '2'

services:

    sample_application:
        container_name: assignment_container
        build: .
        ports:
            - 4126:80
        volumes:
            - "./dist:/var/www/html"
            - "./data:/var/www/html/data"
        restart: unless-stopped

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: my_secret_pw_shh
  #     MYSQL_DATABASE: assignment
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD:
  #   ports:
  #     - "9906:3306"
  # web:
  #   image: php:7.2.2-apache
  #   container_name: assignment_container
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./php/:/var/www/html/
  #   ports:
  #     - "4126:80"
  #   stdin_open: true
  #   tty: true
